//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AQBMetadata.ORMDataModel
{
   public static class ConnectionHelper
   {
      static Type[ ] persistentTypes = new Type[ ] {
         typeof(MetadataItemXpObject)
      };
      public const string ConnectionString = @"XpoProvider=SQLite;Data Source=D:\Users\user01\source\repos\TEST\DXApplication19\DXApplication19\database\TestDB000.db";
      public static void Connect( DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false )
      {
         if( threadSafe )
         {
            var provider = XpoDefault.GetConnectionProvider( ConnectionString, autoCreateOption );
            var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary( );
            dictionary.GetDataStoreSchema( persistentTypes );
            XpoDefault.DataLayer = new ThreadSafeDataLayer( dictionary, provider );
         }
         else
         {
            XpoDefault.DataLayer = XpoDefault.GetDataLayer( ConnectionString, autoCreateOption );
         }
         XpoDefault.Session = null;
      }
      public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider( DevExpress.Xpo.DB.AutoCreateOption autoCreateOption )
      {
         return XpoDefault.GetConnectionProvider( ConnectionString, autoCreateOption );
      }
      public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider( DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[ ] objectsToDisposeOnDisconnect )
      {
         return XpoDefault.GetConnectionProvider( ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect );
      }
      public static IDataLayer GetDataLayer( DevExpress.Xpo.DB.AutoCreateOption autoCreateOption )
      {
         return XpoDefault.GetDataLayer( ConnectionString, autoCreateOption );
      }
   }

}
