//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AQBMetadata.ORMDataModel
{

   public partial class MetadataItemXpObject : XPObject
   {
      string fID;
      public string ID
      {
         get { return fID; }
         set { SetPropertyValue<string>( nameof( ID ), ref fID, value ); }
      }
      string fParentID;
      public string ParentID
      {
         get { return fParentID; }
         set { SetPropertyValue<string>( nameof( ParentID ), ref fParentID, value ); }
      }
      string fDataStoreName;
      public string DataStoreName
      {
         get { return fDataStoreName; }
         set { SetPropertyValue<string>( nameof( DataStoreName ), ref fDataStoreName, value ); }
      }
   }

}
